### ISSUE TITLE
Inconsistency detected by ld.so (openjdk-11, openjdk-12)

### ISSUE THREAD

**Issue by JonasVautherin** [hharrison/java3d-core#28]
I am trying to build from source (using gradle). I manage to build `vecmath`, `java3d-core`, `java3d-utils`. With `java3d-core` linking gluegen-rt and jogl-all:

```
    implementation 'org.jogamp.gluegen:gluegen-rt:2.3.2'
    implementation 'org.jogamp.jogl:jogl-all:2.3.2'
```

However, when running my binary, I get the following error:

```
Starting GUI...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javax.media.j3d.JoglPipeline (file:/home/jones/Documents/px4/tmp/java3d/java3d-core/build/libs/java3d-core-1.6.2.jar) to method sun.awt.AppContext.getAppContext()
WARNING: Please consider reporting this to the maintainers of javax.media.j3d.JoglPipeline
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/user/path/to/jMAVSim/natives/linux-amd64//libgluegen-rt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2620)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
```

It seems to me that `libgluegen-rt.so` comes from `jogamp-fat.jar` (because I see it there when I open the jar). Of course, when I link `jogamp-fat.jar`, I get the following error, which I presume is due to the fact that I am building with openjdk-12 and `jogamp-fat.jar` was built with openjdk-8:

```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

Does that make sense? If yes, now that I am able to build almost everything from source in order to build with openjdk 12, what am I supposed to do about `libgluegen-rt.so`? And shouldn't it be included in 'org.jogamp.gluegen:gluegen-rt:2.3.2'?

**Comment by JonasVautherin** [comment]
So I can build GlueGen and get `libgluegen-rt.so` for my system. And then at runtime I realize I miss another library.

The needed libraries are in `jogamp.jar`:

```
./natives/solaris-i586/libnativewindow_x11.so
./natives/solaris-i586/libjogl_mobile.so
./natives/solaris-i586/libnewt.so
./natives/solaris-i586/libjoal.so
./natives/solaris-i586/libjogl_desktop.so
./natives/solaris-i586/libgluegen-rt.so
./natives/solaris-i586/libjocl.so
./natives/solaris-i586/libnativewindow_awt.so
./natives/linux-amd64/libnativewindow_x11.so
./natives/linux-amd64/libjogl_mobile.so
./natives/linux-amd64/libnewt.so
./natives/linux-amd64/libjoal.so
./natives/linux-amd64/libopenal.so
./natives/linux-amd64/libnativewindow_awt.so
./natives/linux-amd64/libjogl_desktop.so
./natives/linux-amd64/libgluegen-rt.so
./natives/linux-amd64/libjocl.so
./natives/linux-amd64/liboculusvr.so
./natives/linux-i586/libjogl_mobile.so
./natives/linux-i586/liboculusvr.so
./natives/linux-i586/libjoal.so
./natives/linux-i586/libjogl_desktop.so
./natives/linux-i586/libnativewindow_awt.so
./natives/linux-i586/libnewt.so
./natives/linux-i586/libgluegen-rt.so
./natives/linux-i586/libnativewindow_x11.so
./natives/linux-i586/libjocl.so
./natives/linux-i586/libopenal.so
./natives/linux-armv6hf/libjoal.so
./natives/linux-armv6hf/libgluegen-rt.so
./natives/linux-armv6hf/libnewt.so
./natives/linux-armv6hf/libjogl_mobile.so
./natives/linux-armv6hf/libnativewindow_awt.so
./natives/linux-armv6hf/libjocl.so
./natives/linux-armv6hf/libopenal.so
./natives/linux-armv6hf/libjogl_desktop.so
./natives/linux-armv6hf/libnativewindow_x11.so
./natives/solaris-amd64/libjogl_desktop.so
./natives/solaris-amd64/libjogl_mobile.so
./natives/solaris-amd64/libnativewindow_awt.so
./natives/solaris-amd64/libjocl.so
./natives/solaris-amd64/libgluegen-rt.so
./natives/solaris-amd64/libnativewindow_x11.so
./natives/solaris-amd64/libnewt.so
./natives/solaris-amd64/libjoal.so
./natives/linux-armv6/libjogl_mobile.so
./natives/linux-armv6/libgluegen-rt.so
./natives/linux-armv6/libnativewindow_awt.so
./natives/linux-armv6/libjoal.so
./natives/linux-armv6/libjogl_desktop.so
./natives/linux-armv6/libnewt.so
./natives/linux-armv6/libopenal.so
./natives/linux-armv6/libnativewindow_x11.so
./natives/linux-armv6/libjocl.so
```

I guess my real issue is that if I use that `jogamp.so`, I get the `Inconsistency detected by ld.so` error, so I can't build on Java 11/12.

Is there something I can do about that?

**Comment by hharrison** [comment]
I don't really maintain Java3D anymore, but you'll likely have better luck using the Java11 branch of Jogl which is working through these issues. Maybe start here:

http://forum.jogamp.org

**Comment by gouessej** [comment]
@JonasVautherin Look at how it's done in JogAmp's Ardor3D Continuation:
https://jogamp.org/cgit/ardor3d.git/tree/ardor3d-jogl/build.gradle

I'm going to leave Github. Harvey's advice is excellent, rather ask for help on the official JogAmp forum.

**Comment by JonasVautherin** [comment]
Thanks for the tip @gouessej! So I can build an run with those maven dependencies, but I still get the issue with java 12:

```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

I must say I'm out of my depth here, I have no clue what this error means. I just observe that I get it when running with openjdk 11 and 12, but not with openjdk 8.

**Comment by gouessej** [comment]
http://forum.jogamp.org/Fail-to-run-with-openjdk-11-and-openjdk-12-tp4040000.html
